service: simpleMerge

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  timeout: 900
  # deploymentBucket:
  #   name: testencodeinput
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - s3:GetObject
  #     Resource: "arn:aws:S3:::${self:custom.upload-bucket}/*"
  #   - Effect: Allow
  #     Action:
  #       - s3:PutObject
  #     Resource: "arn:aws:S3:::${self:custom.upload-bucket}/*"

# package:
#   individually: true

custom:
  transcoded-chunks-bucket: bento-transcoded-segments
  end-bucket: bento-video-end

functions:
  simpleMerge:
    handler: handler.simpleMerge
    environment:
      TRANSCODED_CHUNKS_BUCKET: "${self:custom.transcoded-chunks-bucket}"
      END_BUCKET: "${self:custom.end-bucket}"
      LD_LIBRARY_PATH: "/opt/awscli/lib"
      PYTHONHOME: "/opt/awscli/lib/python2.7"
      PYTHONPATH: "/opt/awscli/lib/python2.7:/opt/awscli/lib/python2.7/lib-dynload"
    timeout: 900
    layers:
      - ${cf:ffmpeg-layer-dev.FfmpegLayerExport}

